name: ci

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'master'
#    tags:
#      - 'v*'
#  pull_request:
#    branches:
#      - 'master'

env:
  IMAGE_REGISTRY: https://hub.docker.com
  IMAGE_NAME: yang601125163/grok2api-arm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: github.event_name != 'pull_request'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest